core/musl-default: add bits/hwcap.h for loongarch64
[ commit a231acc66354a26968b9addeabc361349b82903c ]

ref:https://www.openwall.com/lists/musl/2024/11/15/2
loongarch64 have cpu feature bits defined in linux for AT_HWCAP auxv entry.

Also fix webkit2gtk-4.1 (2.46.3) error:
error: use of undeclared identifier 'HWCAP_LOONGARCH_LSX'
error: use of undeclared identifier 'HWCAP_LOONGARCH_LASX'