universe/efitools: fix build with gcc 15
[ commit f2624a565bcc991a538060db0c1fcf2ec47b2647 ]

Fix bool typedef error. Also a minor adjustment to `ARCH` variable for linter.

```
In file included from asn1.c:18:
typedefs.h:55:23: error: 'bool' cannot be defined via 'typedef'
   55 | typedef unsigned char bool;
      |                       ^~~~
typedefs.h:55:23: note: 'bool' is a keyword with '-std=c23' onwards
typedefs.h:55:1: warning: useless type name in empty declaration
   55 | typedef unsigned char bool;
      | ^~~~~~~
```