universe/clang16: fix stack protector patch
[ commit 0c49ee2d26adf9fc61dc4d08d21c1ba0cc597b64 ]

libstdc++.a requires a __stack_chk_fail_local reference but if
ssp_nonshared is linked first the symbols are gone and produce:

    undefined reference to `__stack_chk_fail_local'

postponing the "-lssp_nonshared" addition fixes it