universe/py3-virtualenv: move py3-python-discovery to depends
[ commit f1ee383b1b24daa7514fdfd9a5dfc9ac9c0ecb58 ]

Resolve runtime error, found in txt2tags.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.14/site-packages/tox/__main__.py", line 6, in <module>
    run()
    ~~~^^

[...]

  File "/usr/lib/python3.14/site-packages/tox/tox_env/python/api.py", line 14, in <module>
    from virtualenv.discovery.py_spec import PythonSpec
  File "/usr/lib/python3.14/site-packages/virtualenv/discovery/py_spec.py", line 5, in <module>
    from python_discovery import PythonSpec
ModuleNotFoundError: No module named 'python_discovery'
```