universe/rust: use thin-local lto on x86
[ commit b552ac1c49188243b310debeb3b094a94e574540 ]

the x86 package builder is having OOM issues:

  rustc-LLVM ERROR: out of memory
  Buffer allocation failed
  rustc exited with signal: 6 (SIGABRT)
  error: could not compile `rustc_driver` (lib)

previously:

- 511faa73904ebba5f57d733263ae79a9b1353d6a
- 0b56e65fc1704061b9266472ef3efa45a01af984
- faf106afc16fa396862dd7a90d98dedf9858fb1d