universe/collectd: fix build on loongarch64 with abuild 3.14.0
[ commit e34da58a16535b3041467e1e627d6bfe00af76bb ]

>>> collectd-java*: Tracing dependencies...
>>> ERROR: collectd-java*: libjvm.so: path not found
>>> ERROR: collectd-java*: create_apks failed
>>> ERROR: collectd: rootpkg failed

OpenJDK21 places libjvm.so in lib/zero if Zero variant is built,
so modify `patchelf` command to glob for location of libjvm.so.

ref: 7dee419bcad0f3f73fe3392b56622fac22bc2231