universe/libva-glx: upgrade to 2.23.0
[ commit dd5b29d8ca0dca880061670467d5e9db90e2965a ]

https://github.com/intel/libva/releases/tag/2.23.0

Upgrade to match libva version and resolve rebuild error for dependents.

```
>>> noggin: Analyzing dependencies...
ERROR: unable to select packages:
  libva-dev-2.23.0-r0:
    breaks: libva-glx-dev-2.22.0-r0[libva-dev~2.22.0]
    satisfies: libva-glx-dev-2.22.0-r0[pc:libva]
```

Also use `:?` and quote paths for linter/style.