universe/bash-completion: remove conflicting interdiff
[ commit 5fc8418c6904b56de1ce06118049cfa7f000281e ]

	ERROR: patchutils-bash-completion-0.4.4-r0: trying to overwrite usr/share/bash-completion/completions/interdiff owned by bash-completion-2.17.0-r0.