universe/spirv-tools: fix build
[ commit 94ac3ba7cbdcf6eac6dfe663d0724a32fa528374 ]

Add missing `SPV_OPERAND_TYPE_VARIABLE_CAPABILITY` enum to fix build
error.

```
[293/368] Building CXX object source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_mode_setting.cpp.o
ninja: job failed: /usr/bin/c++ -DSPIRV_COLOR_TERMINAL -DSPIRV_TIMER_ENABLED -DSPIRV_Tools_EXPORTS -I/home/buildozer/aports/main/spirv-tools/src/SPIRV-Tools-vulkan-sdk-1.4.321.0 -I/home/buildozer/aports/main/spirv-tools/src/SPIRV-Tools-vulkan-sdk-1.4.321.0/include -I/home/buildozer/aports/main/spirv-tools/src/SPIRV-Tools-vulkan-sdk-1.4.321.0/build -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -g -g1 -flto=auto -Os -DNDEBUG -std=c++17 -fPIC -fno-rtti -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -fno-exceptions -MD -MT source/CMakeFiles/SPIRV-Tools.dir/table2.cpp.o -MF source/CMakeFiles/SPIRV-Tools.dir/table2.cpp.o.d -o source/CMakeFiles/SPIRV-Tools.dir/table2.cpp.o -c /home/buildozer/aports/main/spirv-tools/src/SPIRV-Tools-vulkan-sdk-1.4.321.0/source/table2.cpp
In file included from /home/buildozer/aports/main/spirv-tools/src/SPIRV-Tools-vulkan-sdk-1.4.321.0/source/table2.cpp:115:
/home/buildozer/aports/main/spirv-tools/src/SPIRV-Tools-vulkan-sdk-1.4.321.0/build/core_tables_body.inc:9678:3: error: 'SPV_OPERAND_TYPE_VARIABLE_CAPABILITY' was not declared in this scope; did you mean 'SPV_OPERAND_TYPE_VARIABLE_ID'?
 9678 |   SPV_OPERAND_TYPE_VARIABLE_CAPABILITY, // 748
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   SPV_OPERAND_TYPE_VARIABLE_ID
```