universe/podman: rebuild against gpgme 2.0.1, add makedepends
[ commit c2d0ac60e4649a770fec9cdff10b0b4821ad97e7 ]

Resolves dependency error seen in apx.

```
>>> apx: Analyzing dependencies...
ERROR: unable to select packages:
  so:libgpgme.so.11 (no such package):
    required by: podman-5.7.1-r1[so:libgpgme.so.11]
```

Add python3 and gettext-envsubst to makedepends to resolve rebuild errors.

```
hack/markdown-preprocess
env: can't execute 'python3': No such file or directory
make: *** [Makefile:538: docs/source/markdown/podman-artifact-add.1.md] Error 127
```

```
env BINDIR=/usr/bin ETCDIR=/etc envsubst '$BINDIR;$ETCDIR' < docker/docker.in > /tmp/tmp.IjiFcg
env: can't execute 'envsubst': No such file or directory
make: *** [Makefile:930: install.docker] Error 127
```