universe/mesa: teporarily disable tests
[ commit 382bdde32c0e39879409ce8245e1403086016901 ]

rusticl_test currently fails to build on at least x86*, loongarch64:

	ninja: job failed: rustc -C linker=cc --color=always -C debug-assertions=no -C overflow-checks=no -C embed-bitcode=no --crate-type bin -Cdefault-linker-libraries -C link-arg=-Wl,--allow-shlib-undefined --edition=2021 -Clink-arg=-Wl,-z,pack-relative-relocs -Clink-arg=-Wl,-z,pack-relative-relocs --crate-name rusticl_test --emit dep-info=src/gallium/frontends/rusticl/rusticl_test.p/rusticl_test.d --emit link=src/gallium/frontends/rusticl/rusticl_test -C metadata=b863b06@@rusticl_test@exe -Dclippy::all -Aclippy::collapsible_else_if -Aclippy::needless_lifetimes -Aclippy::question_mark -Dboxed_slice_into_iter -Ddeprecated_safe_2024 -Dimpl_trait_overcaptures -Dkeyword_idents_2024 -Dmissing_unsafe_on_extern -Dnever_type_fallback_flowing_into_unsafe -Drust_2024_prelude_collisions -Dstatic_mut_refs -Dunsafe_op_in_unsafe_fn -Aclippy::assertions_on_constants -Aclippy::mutable_key_type -Aclippy::not_unsafe_ptr_arg_deref -Aclippy::redundant_field_names -Aclippy::too_many_arguments -Aclippy::type_complexity -Amismatched_lifetime_syntaxes --cfg rusticl_enable_auto --cfg glx --test --extern libc_rust_gen=src/gallium/frontends/rusticl/liblibc_rust_gen.rlib --extern mesa_rust=src/gallium/frontends/rusticl/libmesa_rust.rlib --extern mesa_rust_gen=src/gallium/frontends/rusticl/libmesa_rust_gen.rlib -Clink-arg=src/gallium/auxiliary/libgallium.a -Clink-arg=src/compiler/nir/libnir.a -Clink-arg=src/compiler/libcompiler.a -Clink-arg=src/util/libmesa_util.a -Clink-arg=src/util/libmesa_util_clflush.a -Clink-arg=src/util/libmesa_util_clflushopt.a -Clink-arg=src/util/libmesa_util_simd.a -Clink-arg=src/util/blake3/libblake3.a -Clink-arg=src/c11/impl/libmesa_util_c11.a -Clink-arg=src/compiler/clc/liblibmesaclc.a -Clink-arg=src/compiler/spirv/libvtn.a --extern mesa_rust_util=src/gallium/frontends/rusticl/libmesa_rust_util.rlib -Clink-arg=src/gallium/frontends/rusticl/librusticl_c.a --extern rusticl_llvm_gen=src/gallium/frontends/rusticl/librusticl_llvm_gen.rlib --extern rusticl_opencl_gen=src/gallium/frontends/rusticl/librusticl_opencl_gen.rlib --extern rusticl_proc_macros=src/gallium/frontends/rusticl/librusticl_proc_macros.so -Clink-arg=src/gallium/frontends/rusticl/librusticl_test.a -Clink-arg=-fPIC -Clink-arg=/usr/lib/libdrm.so -L/usr/lib/llvm21/lib -Clink-arg=-lLLVM-21 -Clink-arg=-pthread -Clink-arg=-lm -Clink-arg=-pthread -Clink-arg=/usr/lib/libz.so -Clink-arg=/usr/lib/libzstd.so -Clink-arg=-pthread -Clink-arg=-lm -Clink-arg=-pthread -Clink-arg=-lm -Clink-arg=-pthread -Clink-arg=-lm -Clink-arg=/usr/lib/llvm21/lib/libclang-cpp.so -L/usr/lib/llvm21/lib -Clink-arg=-lLLVM-21 -Clink-arg=-pthread -Clink-arg=/usr/lib/libLLVMSPIRVLib.so -Clink-arg=/usr/lib/libSPIRV-Tools-opt.so -Clink-arg=/usr/lib/libSPIRV-Tools.so -Clink-arg=/usr/lib/libSPIRV-Tools-link.so -Clink-arg=-pthread -Clink-arg=-lm -L/usr/lib/rustlib/x86_64-alpine-linux-musl/lib/self-contained -Lsrc/gallium/frontends/rusticl -Lsrc/gallium/auxiliary -Lsrc/compiler/nir -Lsrc/compiler -Lsrc/util -Lsrc/util/blake3 -Lsrc/c11/impl -Lsrc/compiler/clc -Lsrc/compiler/spirv -L/usr/lib -L/usr/lib/llvm21/lib -Clink-arg=-L/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0 -Clink-arg=-L/usr/x86_64-alpine-linux-musl/lib -Clink-arg=-L/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/lib/../lib -Clink-arg=-L/usr/lib -Clink-arg=-L/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../lib -Clink-arg=-L/lib -Clink-arg=-L/lib/../lib -Clink-arg=-L/usr/lib/../lib -Clink-arg=-L/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/lib -Clink-arg=-L/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../.. -Clink-arg=-lstdc++ -C 'link-arg=-Wl,-rpath,$ORIGIN/:/usr/lib/llvm21/lib:/usr/lib/rustlib/x86_64-alpine-linux-musl/lib' ../src/gallium/frontends/rusticl/lib.rs
	error: linking with `cc` failed: exit status: 1
	  |
	  = note:  "cc" "-m64" "/tmp/rustcsy4i0S/symbols.o" "<17 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "<sysroot>/lib/rustlib/x86_64-alpine-linux-musl/lib/{libtest-*,libgetopts-*,librustc_std_workspace_std-*}.rlib" "/builds/alpine/aports/main/mesa/src/mesa-26.0.0/output/src/gallium/frontends/rusticl/{librusticl_llvm_gen,librusticl_opencl_gen,libmesa_rust}.rlib" "-l:libgallium.a" "-l:libnir.a" "-l:libcompiler.a" "-l:libmesa_util.a" "-l:libmesa_util_clflush.a" "-l:libmesa_util_clflushopt.a" "-l:libmesa_util_simd.a" "-l:libblake3.a" "-l:libmesa_util_c11.a" "-l:liblibmesaclc.a" "-l:libvtn.a" "-l:librusticl_c.a" "src/gallium/frontends/rusticl/{libmesa_rust_util,libmesa_rust_gen}.rlib" "-l:libgallium.a" "-l:libnir.a" "-l:libcompiler.a" "-l:libmesa_util.a" "-l:libmesa_util_clflush.a" "-l:libmesa_util_clflushopt.a" "-l:libmesa_util_simd.a" "-l:libblake3.a" "-l:libmesa_util_c11.a" "-l:liblibmesaclc.a" "-l:libvtn.a" "src/gallium/frontends/rusticl/liblibc_rust_gen.rlib" "<sysroot>/lib/rustlib/x86_64-alpine-linux-musl/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,libcfg_if-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,liblibc-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-l:libdrm.so" "-l:libz.so" "-l:libzstd.so" "-l:libclang-cpp.so" "-l:libLLVMSPIRVLib.so" "-l:libSPIRV-Tools-opt.so" "-l:libSPIRV-Tools.so" "-l:libSPIRV-Tools-link.so" "-l:libdrm.so" "-l:libz.so" "-l:libzstd.so" "-l:libclang-cpp.so" "-l:libLLVMSPIRVLib.so" "-l:libSPIRV-Tools-opt.so" "-l:libSPIRV-Tools.so" "-l:libSPIRV-Tools-link.so" "-lgcc_s" "-lc" "-L" "/tmp/rustcsy4i0S/raw-dylibs" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "<sysroot>/lib/llvm21/lib" "-L" "<sysroot>/lib/rustlib/x86_64-alpine-linux-musl/lib/self-contained" "-L" "src/gallium/frontends/rusticl" "-L" "src/gallium/auxiliary" "-L" "src/compiler/nir" "-L" "src/compiler" "-L" "src/util" "-L" "src/util/blake3" "-L" "src/c11/impl" "-L" "src/compiler/clc" "-L" "src/compiler/spirv" "-L" "<sysroot>/lib" "-L" "<sysroot>/lib/rustlib/x86_64-alpine-linux-musl/lib" "-o" "src/gallium/frontends/rusticl/rusticl_test" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,--allow-shlib-undefined" "-Wl,-z,pack-relative-relocs" "-Wl,-z,pack-relative-relocs" "src/gallium/auxiliary/libgallium.a" "src/compiler/nir/libnir.a" "src/compiler/libcompiler.a" "src/util/libmesa_util.a" "src/util/libmesa_util_clflush.a" "src/util/libmesa_util_clflushopt.a" "src/util/libmesa_util_simd.a" "src/util/blake3/libblake3.a" "src/c11/impl/libmesa_util_c11.a" "src/compiler/clc/liblibmesaclc.a" "src/compiler/spirv/libvtn.a" "src/gallium/frontends/rusticl/librusticl_c.a" "src/gallium/frontends/rusticl/librusticl_test.a" "-fPIC" "<sysroot>/lib/libdrm.so" "-lLLVM-21" "-pthread" "-lm" "-pthread" "<sysroot>/lib/libz.so" "<sysroot>/lib/libzstd.so" "-pthread" "-lm" "-pthread" "-lm" "-pthread" "-lm" "<sysroot>/lib/llvm21/lib/libclang-cpp.so" "-lLLVM-21" "-pthread" "<sysroot>/lib/libLLVMSPIRVLib.so" "<sysroot>/lib/libSPIRV-Tools-opt.so" "<sysroot>/lib/libSPIRV-Tools.so" "<sysroot>/lib/libSPIRV-Tools-link.so" "-pthread" "-lm" "-L<sysroot>/lib/gcc/x86_64-alpine-linux-musl/15.2.0" "-L<sysroot>/x86_64-alpine-linux-musl/lib" "-L<sysroot>/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/lib/../lib" "-L<sysroot>/lib" "-L<sysroot>/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../lib" "-L/lib" "-L/lib/../lib" "-L<sysroot>/lib/../lib" "-L<sysroot>/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/lib" "-L<sysroot>/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../.." "-lstdc++" "-Wl,-rpath,$ORIGIN/:<sysroot>/lib/llvm21/lib:<sysroot>/lib/rustlib/x86_64-alpine-linux-musl/lib"
	  = note: some arguments are omitted. use `--verbose` to show all linker arguments
	  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: src/gallium/frontends/rusticl/rusticl_test: hidden symbol `floor' in /usr/lib/rustlib/x86_64-alpine-linux-musl/lib/libcompiler_builtins-81e55c1928744c23.rlib(compiler_builtins-81e55c1928744c23.compiler_builtins.eff7ed6db33fccd0-cgu.195.rcgu.o) is referenced by DSO
	          /usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: final link failed: bad value
	          collect2: error: ld returned 1 exit status

	error: aborting due to 1 previous error

To be investigated.

Signed-off-by: Achill Gilgenast <achill@achill.org>