universe/virtualbox-guest-additions: fix build with gcc 15
[ commit 6a5c2cb3b6922b76e8e16da8611b8a949bf50547 ]

Fix bool typedef error.

Also use a full path in the `install` command within the `udev()`
function to ensure the file can be found.

```
In file included from /home/buildozer/aports/community/virtualbox-guest-additions/src/VirtualBox-7.0.22/src/VBox/Runtime/common/misc/sanity.h:38,
                 from /home/buildozer/aports/community/virtualbox-guest-additions/src/VirtualBox-7.0.22/src/VBox/Runtime/common/misc/sanity-c.c:37:
/home/buildozer/aports/community/virtualbox-guest-additions/src/VirtualBox-7.0.22/include/iprt/types.h:285:15: error: 'bool' cannot be defined via 'typedef'
  285 | typedef _Bool bool;
      |               ^~~~
/home/buildozer/aports/community/virtualbox-guest-additions/src/VirtualBox-7.0.22/include/iprt/types.h:285:15: note: 'bool' is a keyword with '-std=c23' onwards
/home/buildozer/aports/community/virtualbox-guest-additions/src/VirtualBox-7.0.22/include/iprt/types.h:285:1: warning: useless type name in empty declaration
  285 | typedef _Bool bool;
      | ^~~~~~~
```