core/docbook-xsl: register also URIs with version "current"
[ commit 4e21aff3a888239f6776f3c84e09d48e5c3a40ae ]

This is needed for building PostgreSQL man pages.

    /usr/bin/xsltproc --nonet --path . --path . --stringparam pg.version '17.0'  stylesheet-man.xsl postgres-full.xml
    I/O error : unsupported protocol: https
    warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
    compilation error: file stylesheet-man.xsl line 7 element import
    xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl