universe/py3-mypy: add missing dependency py3-pathspec
[ commit fa9d8df50f52f1adeeadf333c45901aafd86a628 ]

Running mypy fails with:

    > mypy
    Traceback (most recent call last):
      File "/usr/bin/mypy", line 5, in <module>
        from mypy.__main__ import console_entry
      File "/usr/lib/python3.12/site-packages/mypy/__main__.py", line 9, in <module>
        from mypy.main import main, process_options
      File "/usr/lib/python3.12/site-packages/mypy/main.py", line 16, in <module>
        from mypy import build, defaults, state, util
      File "/usr/lib/python3.12/site-packages/mypy/build.py", line 76, in <module>
        from mypy.modulefinder import (
      File "/usr/lib/python3.12/site-packages/mypy/modulefinder.py", line 19, in <module>
        from pathspec import PathSpec
    ModuleNotFoundError: No module named 'pathspec'

Add the missing dependency for mypy to work.