universe/clang20: add so version to py3-clang20
[ commit 23670b14d3db79d08ab73c7a7ceb94bef1e7c85a ]

As of now, running the following python code

    from clang import cindex
    cindex.Index.create()

fails with:

    [...]
    clang.cindex.LibclangError: Error loading shared library libclang.so:
    No such file or directory. To provide a path to libclang use
    Config.set_library_path() or Config.set_library_file().

This could be fixed by patching every user to call

    cindex.Config.set_library_file("/usr/lib/libclang.so.20.1.3")

before calling `cindex.Index.create()`. But adding the version of the
library to the expected file name to match the installed file saves us
this trouble.