universe/py3-typing-extensions: fix tests with python 3.14
[ commit bd6d47dd15411d61eb104d961b72b31a62d28d09 ]

Fix `test_inheritance_pep563` tests with python 3.14.

```
FAIL: test_inheritance_pep563 (__main__.TypedDictTests.test_inheritance_pep563) (base_future=True, child_future=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/aports/main/py3-typing-extensions/src/typing_extensions-4.15.0/src/test_typing_extensions.py", line 4443, in test_inheritance_pep563
    self.assertEqual(base.__annotations__, {'base': base_anno})
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'base': ForwardRef('int', module='builtins', owner=<class 'Base'>)} != {'base': ForwardRef('int',
module='builtins')}
- {'base': ForwardRef('int', module='builtins', owner=<class 'Base'>)}
?                                             ----------------------

+ {'base': ForwardRef('int', module='builtins')}
```

Failed tests:

```
FAIL: test_inheritance_pep563 (__main__.TypedDictTests.test_inheritance_pep563) (base_future=True, child_future=True)
FAIL: test_inheritance_pep563 (__main__.TypedDictTests.test_inheritance_pep563) (base_future=True, child_future=False)
FAIL: test_inheritance_pep563 (__main__.TypedDictTests.test_inheritance_pep563) (base_future=False, child_future=True)
```