core/glibc: add missing SUPPORTED file to fix locale-gen
locale-gen relies on the /usr/share/i18n/SUPPORTED file:

  locale-gen en_US.UTF-8
  grep: /usr/share/i18n/SUPPORTED: No such file or directory
  grep: /usr/share/i18n/SUPPORTED: No such file or directory
  grep: /usr/share/i18n/SUPPORTED: No such file or directory
  Error: 'en_US.UTF-8' is not a supported language or locale

Also, add a space to the comments in the /etc/locale.gen to
make the file more readable (locale-gen supports this).