universe/ghostscript: fix build with gcc 15
[ commit a87bbe41d0a8f5481a469a357abb68aeedb35cd9 ]

Backport upstream patches to fix bool typedef and other errors.
Disable some filters which failed to rebuild and were already removed upstream
in the main branch.

```
./psi/zfaes.c: In function 'z_aes_d':
./psi/zfaes.c:53:43: error: passing argument 4 of 'dict_bool_param' from incompatible pointer type [-Wincompatible-pointer-types]
   53 |     if (dict_bool_param(op, "Padding", 1, &use_padding) < 0)
      |                                           ^~~~~~~~~~~~
      |                                           |
      |                                           int *
In file included from ./psi/zfaes.c:27:
./psi/idparam.h:41:45: note: expected '_Bool *' but argument is of type 'int *'
   41 |                     bool defaultval, bool * pvalue);
      |                                      ~~~~~~~^~~~~~
```