universe/oath-toolkit: rebuild for xmlsec 1.3.11
[ commit a97ea3b450a0566902282c111110bf35556c8572 ]

Fixes:

    ERROR: unable to select packages:
      so:libxmlsec1.so.1 (no such package):
        required by: oath-toolkit-libpskc-2.6.14-r0[so:libxmlsec1.so.1]