universe/py3-poetry-core: fix checksum
[ commit 309a4daa6c2608ea52295212f4473a4ab6392e29 ]

Fix checksum error found on the edge builders.

```
ERROR: py3-poetry-core: Number of checksums(4 / 2) does not correspond
to number of sources(1)
```