core/gcc: fix libgcc-static cross-bootstrap
[ commit 2aa0eaee55c85d8e8bef5c058c6eb200f1c0243f ]

When bootstraping on x86_64 via './scripts/bootstrap.sh aarch64',
gcc-aarch64 has dependency libgcc-static-aarch64. The former is a native
package, but the latter is cross-compiled only, so cannot be installed,
and the bootstrap process fails:

    >>> build-base-aarch64: Analyzing dependencies...
    ERROR: unable to select packages:
      libgcc-static-aarch64 (no such package):
        required by: gcc-aarch64-15.2.0-r6[libgcc-static-aarch64]
      .makedepends-build-base-aarch64-20260701.212613:
        masked in: cache
        satisfies: world[.makedepends-build-base-aarch64=20260701.212613]
    >>> ERROR: build-base-aarch64: builddeps failed
    >>> build-base-aarch64: Uninstalling dependencies...
    ERROR: No such package: .makedepends-build-base-aarch64
    ERROR: No such package: .hostdepends-build-base-aarch64

Build libgcc-static-aarch64 for the host architecture instead.

See also: fd4fecacbfd0cd40be42efa3c9d72bc03a88428c