universe/libxxf86vm: explicitly specify --libdir=/usr/lib
For some reason, an abuild-meson script which specifies
--libdir=/usr/lib is not used here. This leads to the following error
when building on glibc:

  >>> ERROR: libxxf86vm*: Packages must not put anything under /usr/lib64, use /usr/lib instead

(cherry picked from commit 6c5128fc743ab00049555a24ca2c1d0286d755ed)