core/glib: move py3-packaging to depends_dev
[ commit e131f4351513318e29d8e70ba5c00c2174c3ba46 ]

Without this, gdbus-codegen fails immediately with:

Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'

Discovered while building community/phosh:

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/63535