core/openjdk11-lite: fix installation of liberica11-lite-doc
Currently, it fails as follows:

  $ apk add liberica11-lite-doc
  ERROR: unable to select packages:
    liberica11-lite-jre-doc-11.0.22_p12-r0:
      conflicts: liberica11-lite-doc-11.0.22_p12-r0[openjdk11-lite-doc=11.0.22_p12-r0]
      satisfies: liberica11-lite-doc-11.0.22_p12-r0[liberica11-lite-jre-doc=11.0.22_p12-r0]
    liberica11-lite-doc-11.0.22_p12-r0:
      conflicts: liberica11-lite-jre-doc-11.0.22_p12-r0[openjdk11-lite-doc=11.0.22_p12-r0]
      satisfies: world[liberica11-lite-doc]