core/ifupdown-ng: fix building for glibc
Starting with commit 571786a ("Makefile: Make gcc be more pendantic and bail
out on warnings") in upstream, ifupdown-ng is built with -Werror flag.  It
causes this kind of errors:

  libifupdown/interface.c: In function 'lif_address_parse':
  libifupdown/interface.c:28:9: error: implicit declaration of function 'strlcpy'; did you mean 'strncpy'? [-Werror=implicit-function-declaration]
     28 |         strlcpy(buf, presentation, sizeof buf);
        |         ^~~~~~~
        |         strncpy

So, let's build it with -Wno-error=implicit-function-declaration for glibc.