core/glib: rebuild to regenerate index
[ commit 7b672d30df3d460ca8c2a9124d33a3eac504a517 ]

	(1/1) Upgrading glib-doc (2.84.4-r2 -> 2.86.0-r0)
	ERROR: glib-doc-2.86.0-r0: v2 package integrity error

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/89858#note_541875