universe/rust: fix conflicts with libstd/librustc_driver-*.so
"apk add rustc-dev" failure:

  ERROR: unable to select packages:
    rust-1.79.0-r0:
      conflicts: rustc-dev-1.79.0-r0[so:librustc_driver-073f76c756e56f45.so=0] rustc-dev-1.79.0-r0[so:libstd-c0bc3174c09c215a.so=0]
      satisfies: rustc-dev-1.79.0-r0[rust=1.79.0-r0]
    rustc-dev-1.79.0-r0:
      conflicts: rust-1.79.0-r0[so:librustc_driver-073f76c756e56f45.so=0] rust-1.79.0-r0[so:libstd-c0bc3174c09c215a.so=0]
      satisfies: world[rustc-dev]