universe/nlohmann-json: fix char8_t support
[ commit f6bce31be10a7a470538148c410cfbb580bad57b ]

Fix `char8_t` detection in the serialiser.
Resolves build error in openrct2.

```
In file included from /usr/include/nlohmann/adl_serializer.hpp:14,
                 from /usr/include/nlohmann/json.hpp:34,
                 from /home/buildozer/aports/community/openrct2/src/OpenRCT2-0.5.5/src/openrct2/rct12/../core/Json.hpp:14,
                 from /home/buildozer/aports/community/openrct2/src/OpenRCT2-0.5.5/src/openrct2/rct12/ScenarioPatcher.cpp:20:
/usr/include/nlohmann/detail/conversions/from_json.hpp: In function 'void nlohmann::json_abi_v3_12_0::detail::from_json(const BasicJsonType&, std::filesystem::__cxx11::path&)':
/usr/include/nlohmann/detail/conversions/from_json.hpp:544:27: error: 'u8string_view' is not a member of 'std'; did you mean 'wstring_view'? [-Wtemplate-body]
  544 |     p = std_fs::path(std::u8string_view(reinterpret_cast<const char8_t*>(s.data()), s.size()));
      |                           ^~~~~~~~~~~~~
      |                           wstring_view
/usr/include/nlohmann/detail/conversions/from_json.hpp:544:21: error: expected primary-expression before '(' token [-Wtemplate-body]
  544 |     p = std_fs::path(std::u8string_view(reinterpret_cast<const char8_t*>(s.data()), s.size()));
      |                     ^
/usr/include/nlohmann/detail/conversions/from_json.hpp:544:27: error: 'u8string_view' is not a member of 'std'; did you mean 'wstring_view'? [-Wtemplate-body]
  544 |     p = std_fs::path(std::u8string_view(reinterpret_cast<const char8_t*>(s.data()), s.size()));
      |                           ^~~~~~~~~~~~~
      |                           wstring_view
/usr/include/nlohmann/detail/conversions/from_json.hpp:544:64: error: expected '>' before 'char8_t' [-Wtemplate-body]
  544 |     p = std_fs::path(std::u8string_view(reinterpret_cast<const char8_t*>(s.data()), s.size()));
      |                                                                ^~~~~~~
In file included from /usr/include/nlohmann/adl_serializer.hpp:15:
/usr/include/nlohmann/detail/conversions/to_json.hpp: In function 'void nlohmann::json_abi_v3_12_0::detail::to_json(BasicJsonType&, const std::filesystem::__cxx11::path&)':
/usr/include/nlohmann/detail/conversions/to_json.hpp:447:16: error: 'u8string' in namespace 'std' does not name a type [-Wtemplate-body]
  447 |     const std::u8string s = p.u8string();
      |                ^~~~~~~~
/usr/include/nlohmann/detail/conversions/to_json.hpp:26:1: note: 'std::u8string' is defined in header '<string>'; this is probably fixable by adding '#include <string>'
   25 | #include <nlohmann/detail/iterators/iteration_proxy.hpp>
  +++ |+#include <string>
   26 | #include <nlohmann/detail/meta/cpp_future.hpp>
```