core/openssh: fix building with gcc14 on glibc
 loginrec.c: In function 'syslogin_perform_login':
gcc13:loginrec.c:1424:9: warning: implicit declaration of function 'login'; did you mean 'logit'? [-Wimplicit-function-declaration]
gcc14:loginrec.c:1424:9: error: implicit declaration of function 'login'; did you mean 'logit'? [-Wimplicit-function-declaration]
  1424 |         login(ut);
       |         ^~~~~
       |         logit

To fix this, we can align glibc variant with musl (no login function)
by specifing that we don't have login/logout() in configure.

Alternatively, we can just use glibc's utmp instead of extrenal utmps pkg,
which conflicts with the glibc's utmp.h include (utmps pkg has utmp.h stub
in /usr/include/utmps/).