universe/py3-cffi: fix tests
[ commit 4688a3c2dbc318cbf332fa8ba30cdd72eafd732a ]

Fix tests in `testing/cffi0/test_parsing.py`. Example error:

```
_________________ test_dont_remove_comment_in_line_directives __________________

    def test_dont_remove_comment_in_line_directives():
        ffi = FFI(backend=FakeBackend())
        e = pytest.raises(CDefError, ffi.cdef, """
            \t # \t line \t 8 \t "baz.c" \t

            some syntax error here
        """)
>       assert str(e.value) == "parse error\nbaz.c:9:14: before: syntax"
E       AssertionError: assert 'parse error\...on definition' == 'parse error\...efore: syntax'
E
E           parse error
E         - baz.c:9:14: before: syntax
E         + baz.c:9:9: Invalid function definition

testing/cffi0/test_parsing.py:200: AssertionError
```

```
FAILED testing/cffi0/test_parsing.py::test_dont_remove_comment_in_line_directives
FAILED testing/cffi0/test_parsing.py::test_multiple_line_directives - Asserti...
FAILED testing/cffi0/test_parsing.py::test_commented_line_directive - Asserti...
FAILED testing/cffi0/test_parsing.py::test_unknown_name - assert False
```