universe/cvs: pass _GNU_SOURCE to build with gcc 14 with glibc
Observing the following issue with glibc:

  In file included from cvs.h:62,
                   from add.c:33:
  add.c: In function 'build_entry':
  ../lib/unlocked-io.h:81:22: error: implicit declaration of function 'fputs_unlocked' [-Wimplicit-function-declaration]
     81 | #  define fputs(x,y) fputs_unlocked (x,y)
        |                      ^~~~~~~~~~~~~~
  add.c:909:20: note: in expansion of macro 'fputs'
    909 |     if (message && fputs (message, fp) == EOF)

Both musl and glibc ship fputs_unlocked(). They make it available
if the _GNU_SOURCE feature macro is defined, so let's define it
globally. It also matches what Debian/Ubuntu do in their patch.