core/libcap-ng: bump pkgrel
[ commit 5b2ac7dd1021903c1b1c257f13c905bd9151f846 ]

pkgrel must be bumped for change to the package, and also solves the
confusion of the mirror caches:

	(184/656) Installing libcap-ng (0.8.5-r0)
	ERROR: libcap-ng-0.8.5-r0: v2 package integrity error

Fixes: 311c4d3092eb ("main/libcap-ng: add py3-libcap-ng subpackage")