universe/catch2: build without Werror
[ commit aa4ddefbe4f87b0d0d430b1ac5e62dbaa495eaf3 ]

fails on armv7:
    /home/buildozer/aports/community/catch2/src/Catch2-2.13.10/projects/SelfTest/UsageTests/ToStringGeneral.tests.cpp:122:32: error: value computed is not used [-Werror=unused-value]
      122 |     std::string_view view{"abc"};
          |                                ^
    cc1plus: all warnings being treated as errors