universe/nodejs26: upgrade to 26.10.0
[ commit 1d5d583f79ca98335fcb6dd2b5e9c9ad5b3eb88b ]

Switch to vendored simdutf to resolve "undefined reference to simdutf::find".