universe/wasi-libc: build with non-default clang
[ commit 4317e6a9007e3775390d942006bcf0b1fbd9853d ]

Building with clang 20 results in the error below, found on the 3.22
builders. Rebuild with clang 19 for now.

```
-Wno-bitwise-op-parentheses -Wno-logical-op-parentheses -Wno-string-plus-int -Wno-dangling-else -Wno-unknown-pragmas -MD -MP -o
↪build/wasm32-wasi/libc-top-half/musl/src/string/memcpy.o -c libc-top-half/musl/src/string/memcpy.c
libc-top-half/musl/src/string/memcpy.c:8:10: error: use of undeclared identifier 'BULK_MEMORY_THRESHOLD'
    8 |         if (n > BULK_MEMORY_THRESHOLD)
      |                 ^
```