universe/libsecret: remove -bash-completion subpackage
[ commit 03f14050378d5478ea231b961c779131001057ff ]

already managed by main/bash-completion

	ERROR: libsecret-bash-completion-0.21.6-r0: trying to overwrite usr/share/bash-completion/completions/secret-tool owned by bash-completion-2.14.0-r1.