universe/libsecret: "downgrade" on riscv64
[ commit b6008018f8995a41de29fdb376f2f9b68636321e ]

[138/146] Generating libsecret/libsecret-1.vapi with a custom command
[139/146] Generating libsecret/Secret-1.typelib with a custom command
ninja: job terminated due to signal 11: /usr/bin/vapigen --quiet --library=libsecret-1 --directory=/home/buildozer/aports/main/libsecret/src/libsecret-0.21.3/output/libsecret --metadatadir=/home/bu
ildozer/aports/main/libsecret/src/libsecret-0.21.3/libsecret --pkg=gobject-2.0 --pkg=gio-2.0 --metadatadir=/home/buildozer/aports/main/libsecret/src/libsecret-0.21.3/libsecret /home/buildozer/aport
s/main/libsecret/src/libsecret-0.21.3/output/libsecret/Secret-1.gir
ninja: subcommand failed
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/buildozer/aports/main/libsecret/src/libsecret-0.21.3/output
>>> ERROR: libsecret: build failed