universe/rust: rebuild with llvm17
[ commit 0a8a69f5c8c9a6dcc8ac79fa689af8fdb6a3d7a8 ]

Actually, we already build rust with llvm17 but this upstream commit
brings changes regarding the compare_bytes intrinsic.  The next rust
upgrade must be built by the rust that contains those changes. Otherwise
the build will fail as follows:

  error[E0093]: unrecognized intrinsic function: `compare_bytes`
      --> library/core/src/intrinsics.rs:2408:5
       |
  2408 |     pub fn compare_bytes(left: *const u8, right: *const u8, bytes: usize) -> i32;
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unrecognized intrinsic