core/bsd-compat-headers: make it dummy on glibc as it is used to be
bsd-compat-headers on glibc was always dummy. Currently it conflicts with
glibc-dev:

  $ apk add bsd-compat-headers
  (1/1) Installing bsd-compat-headers (0.7.2-r6)
  ERROR: bsd-compat-headers-0.7.2-r6: trying to overwrite usr/include/sys/cdefs.h owned by glibc-dev-2.37.0-r11.
  ERROR: bsd-compat-headers-0.7.2-r6: trying to overwrite usr/include/sys/queue.h owned by glibc-dev-2.37.0-r11.
  1 error; 346 MiB in 83 packages