universe/imap: update source url
[ commit 07d21066025164a8e50a35efbc7eb699e2339950 ]

Update the url to use an alternative source (the checksum has not changed).

```
>>> imap: Fetching http://ftp.ntua.gr/pub/net/mail/imap/imap-2007f.tar.gz
Connecting to ftp.ntua.gr (147.102.222.211:80)
wget: can't connect to remote host (147.102.222.211): Connection refused
>>> ERROR: imap: fetch failed
```