core/utmps: rebuild to fix utmp-libs on riscv64
[ commit 0a2095d44d0e49b107f1d42d664697b554c0fb20 ]

Installing utmps-libs (0.1.3.2-r0)
ERROR: utmps-libs-0.1.3.2-r0: v2 package integrity error