universe/rust: allow net access in rootbld
[ commit c9f5304f47a5ca8446c62edc77d1963915b1eb33 ]

needed for some crates:
```
    Finished `release` profile [optimized] target(s) in 0.46s
Dist clippy-1.85.1-x86_64-alpine-linux-musl
	finished in 0.468 seconds
Skipping RustDev (x86_64-alpine-linux-musl): external LLVM
Dist extended stage1 (x86_64-alpine-linux-musl)
Dist rust-1.85.1-x86_64-alpine-linux-musl
	finished in 11.628 seconds
STDERR:
    Updating crates.io index
warning: spurious network error (3 tries remaining): [6] Could not resolve hostname (Could not resolve host: index.crates.io)
warning: spurious network error (2 tries remaining): [6] Could not resolve hostname (Could not resolve host: index.crates.io)
warning: spurious network error (1 tries remaining): [6] Could not resolve hostname (Could not resolve host: index.crates.io)
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to get `unicode-ident` as a dependency of package `build-rs v0.3.0 (/tmp/src/rustc-1.85.1-src/src/tools/cargo/crates/build-rs)`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `https://index.crates.io/config.json`

Caused by:
  [6] Could not resolve hostname (Could not resolve host: index.crates.io)

Command cd "/tmp/src/rustc-1.85.1-src/build/tmp/tarball/rustc/src/image" && RUSTC_BOOTSTRAP="1" "/usr/bin/cargo" "vendor" "--versioned-dirs" "--sync" "/tmp/src/rustc-1.85.1-src/src/tools/cargo/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/src/tools/rust-analyzer/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/compiler/rustc_codegen_cranelift/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/compiler/rustc_codegen_gcc/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/library/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/src/bootstrap/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/src/tools/rustbook/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/src/tools/rustc-perf/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/src/tools/opt-dist/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/src/doc/book/packages/trpl/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/syn-1.0.89/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/cargo-0.60.0/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/serde-1.0.136/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/ripgrep-13.0.0/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/regex-1.5.5/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/clap-3.1.6/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/hyper-0.14.18/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/externs/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/ctfe-stress-5/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/cargo-0.60.0/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/token-stream-stress/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/match-stress/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/tuple-stress/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/diesel-1.4.8/Cargo.toml" "--sync" "/tmp/src/rustc-1.85.1-src/./src/tools/rustc-perf/collector/compile-benchmarks/bitmaps-3.1.0/Cargo.toml" (failure_mode=Exit) has failed. Rerun with -v to see more details.
```