universe/py3-fontmath: fix installer .whl filename
[ commit fe471d4589e4b9848680ba3d1772361bde9c83ce ]

Fix packaging error due to changed .whl filename with setuptools >= 75.3.1.

```
FileNotFoundError: [Errno 2] No such file or directory: '.dist/fontMath-*.whl'
```