universe/py3-referencing: depend on py3-typing-extensions
[ commit cacfa25bf878ae3790ab825901f87b265d76c48a ]

	>>> import referencing
	[...]
	TypeError: 'default' is an invalid keyword argument for typevar()

Ref: https://github.com/python-jsonschema/referencing/issues/216
Closes: https://gitlab.alpinelinux.org/alpine/aports/-/issues/16877